language: ruby
cache: bundler

rvm:
  - 1.9.3

before_install:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script: 'bundle install'
script: 'bundle exec cucumber'

branches:
  only:
    - master

notifications:
  email:
    - isakib@gmail.com
